#!/usr/bin/env python3
"""Validate vibe-coding-launcher project documentation.

Checks:
- Core documents exist (AGENTS.md, WORKFLOW.md or lightweight alternative,
  validate_agents_docs.py, ARCHITECTURE.md or CLI alternative,
  EXECUTION_GATES.md or AGENTS.md gate summary; TASKS.md optional)
- AGENTS.md sections complete (simplified or full version)
- Root AGENTS.md must declare explicit constraint mechanism
- Root AGENTS.md must contain the verbatim workflow hard constraint
  ("MUST NOT skip documentation ... Lightweight path ONLY for trivial
  changes as defined in WORKFLOW.md.")
- Root AGENTS.md must preserve the active ExecPlan execution gate markers.
- TASKS.md uses standard sections and per-task validation conditions (if exists)
- Quick-entry links in AGENTS.md are valid
- Line count within limits

Severity levels:
- ERROR: Must fix before proceeding
- WARN: Requires resolution or documented risk acceptance before advancement or completion
- INFO: Status information
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from enum import Enum
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


class Severity(Enum):
    ERROR = "ERROR"
    WARN = "WARN"
    INFO = "INFO"


@dataclass
class ValidationResult:
    path: Path
    severity: Severity
    message: str

    def __str__(self) -> str:
        level = self.severity.value
        rel_path = self.path.relative_to(ROOT) if self.path.is_relative_to(ROOT) else self.path
        return f"[{level}] {rel_path}: {self.message}"


# Canonical English headings with legacy Chinese aliases. Root-level Constraint
# Mechanism is validated separately so child AGENTS.md files can inherit it.
SIMPLE_REQUIRED = {
    "Quick Entry": ("Quick Entry", "快速入口"),
    "Core Beliefs": ("Core Beliefs", "核心信念"),
    "Development Workflow": ("Development Workflow", "开发流程"),
    "Common Commands": ("Common Commands", "常用命令"),
}

# Mature-version headings are already language-neutral.
FULL_REQUIRED = ["Scope", "Do", "Avoid", "Commands", "Tests", "Related Skills"]

# Line-count limits
MIN_LINES = 20
MAX_SIMPLE_LINES = 150
MAX_FULL_LINES = 140

# Generated-comment pattern. Keep the legacy alias for existing projects.
GEN_COMMENT_PATTERN = re.compile(
    r"<!-- (?:Generated by vibe-coding-launcher|由 vibe-coding-launcher 生成).*-->",
    re.IGNORECASE,
)

# TASKS.md protocol: English is canonical; Chinese aliases remain compatible.
TASK_REQUIRED_SECTIONS = {
    "In Progress": ("In Progress", "进行中"),
    "To Do": ("To Do", "待办"),
    "Completed": ("Completed", "已完成"),
}
CHECKBOX_PATTERN = re.compile(r"^- \[[ x]\]\s+")
PENDING_TASK_PATTERN = re.compile(r"^- \[ \]\s+")
COMPLETED_TASK_PATTERN = re.compile(r"^- \[x\]\s+")
TASK_VALIDATION_MARKER = "✅"

# Quick Entry links
QUICK_ENTRY_PATTERN = re.compile(r"`([^`]+\.md)`")

CONSTRAINT_SECTIONS = ("Constraint Mechanism", "约束机制")
CONSTRAINT_MODE_PATTERN = re.compile(r"(?:Mode|模式)[：:]\s*`([^`]+)`", re.IGNORECASE)
CONSTRAINT_CONFIG_PATTERN = re.compile(
    r"(?:Configuration|Config|配置)[：:]\s*`([^`]+)`",
    re.IGNORECASE,
)
VALID_CONSTRAINT_MODES = {"agents-only", "linter+agents"}

# Root AGENTS.md must preserve these workflow markers verbatim. Checking the
# phrases rather than the full line allows harmless formatting differences.
WORKFLOW_CONSTRAINT_MARKERS = (
    "MUST NOT skip documentation for non-trivial tasks",
    "Lightweight path ONLY for trivial changes as defined in WORKFLOW.md",
)
ACTIVE_EXECPLAN_CONSTRAINT_MARKERS = (
    "Formal coding starts only after reading the approved active ExecPlan",
    "Treat the active ExecPlan as the execution source of truth",
)

ARCHITECTURE_CONCEPT_GROUPS = {
    "overview": ["Overview", "概述"],
    "module or code map": ["Code Map", "Module", "Modules", "代码地图", "模块"],
    "key files": ["Key Files", "关键文件"],
    "architecture constraints or invariants": ["Invariant", "Boundary", "不变量", "边界"],
}


def is_cli_project(root: Path) -> bool:
    """Detect CLI/single-file project by directory structure.

    A project is considered CLI/single-file if it has no src/ directory
    and either has no docs/ directory, or docs/ only contains exec-plans/
    (which is auto-generated for ExecPlan tracking and does not indicate
    a non-CLI project structure).
    """
    if (root / "src").exists():
        return False

    docs_dir = root / "docs"
    if not docs_dir.exists():
        return True

    # docs/ exists; check whether it contains only the conditional exec-plans/ directory.
    entries = [p for p in docs_dir.iterdir()]
    if len(entries) == 1 and entries[0].name == "exec-plans":
        return True

    return False


def detect_version(headings: list[str]) -> str:
    """Detect AGENTS.md version (simplified or full)."""
    if "Scope" in headings:
        return "full"
    return "simple"


def extract_section_lines(lines: list[str], heading: str) -> list[str]:
    """Extract lines belonging to a markdown H2 section."""
    section_lines: list[str] = []
    in_section = False

    for line in lines:
        stripped = line.strip()
        if stripped == f"## {heading}":
            in_section = True
            continue
        if in_section and stripped.startswith("## "):
            break
        if in_section:
            section_lines.append(line)

    return section_lines


def find_section_lines(lines: list[str], headings: tuple[str, ...]) -> list[str]:
    """Return the first matching section from canonical or legacy headings."""
    for heading in headings:
        section_lines = extract_section_lines(lines, heading)
        if section_lines:
            return section_lines
    return []


def has_heading(headings: list[str], aliases: tuple[str, ...]) -> bool:
    """Return whether any canonical or legacy heading is present."""
    return any(alias in headings for alias in aliases)


def parse_constraint_mechanism(lines: list[str]) -> tuple[str | None, str | None]:
    """Parse mode/config from the canonical or legacy constraint section."""
    section_lines = find_section_lines(lines, CONSTRAINT_SECTIONS)
    if not section_lines:
        return None, None

    mode: str | None = None
    config: str | None = None
    for line in section_lines:
        if mode is None:
            match = CONSTRAINT_MODE_PATTERN.search(line)
            if match:
                mode = match.group(1)
        if config is None:
            match = CONSTRAINT_CONFIG_PATTERN.search(line)
            if match:
                config = match.group(1)

    return mode, config


def read_text_if_exists(path: Path) -> str:
    """Read a UTF-8 markdown file, returning empty text when absent."""
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return ""


def agents_has_lightweight_workflow(agents_md: Path) -> bool:
    """Detect an AGENTS.md workflow alternative for tiny projects."""
    content = read_text_if_exists(agents_md)
    return (
        "轻量流程" in content
        or "Lightweight Path" in content
        or ("轻量" in content and "流程" in content)
    )


def agents_has_execution_gate_summary(agents_md: Path) -> bool:
    """Detect a compact completion-gate summary in AGENTS.md."""
    content = read_text_if_exists(agents_md)
    has_gate_label = (
        "Completion Gates" in content
        or "完成门禁" in content
        or "收尾标准" in content
        or "Definition Of Done" in content
        or "Hard Gates" in content
    )
    has_validation_signal = (
        "Validation" in content
        or "验证" in content
        or "Residual risk" in content
        or "残余风险" in content
    )
    return has_gate_label and has_validation_signal


def validate_agents_md(
    path: Path,
    min_level: Severity,
    *,
    cli_project: bool = False,
    require_constraint_mechanism: bool = False,
    require_workflow_constraint: bool = False,
) -> list[ValidationResult]:
    """Validate one AGENTS.md file."""
    results: list[ValidationResult] = []

    if not path.exists():
        results.append(ValidationResult(path, Severity.ERROR, "file does not exist"))
        return results

    content = path.read_text(encoding="utf-8")
    lines = content.splitlines()
    line_count = len(lines)

    # Check line count.
    if line_count < MIN_LINES:
        results.append(ValidationResult(path, Severity.ERROR, f"too few lines: {line_count} < {MIN_LINES}"))

    # Extract section headings.
    headings: list[str] = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("## ") and not stripped.startswith("## #"):
            heading = stripped[3:].strip()
            headings.append(heading)

    # Detect template version.
    version = detect_version(headings)

    if version == "full":
        # Mature template checks.
        if line_count > MAX_FULL_LINES:
            results.append(ValidationResult(path, Severity.WARN, f"mature version exceeds line limit: {line_count} > {MAX_FULL_LINES}"))

        for section in FULL_REQUIRED:
            if section not in headings:
                results.append(ValidationResult(path, Severity.ERROR, f"mature version missing section: {section}"))

        results.append(ValidationResult(path, Severity.INFO, f"mature, {line_count} lines"))
    else:
        # Simplified template checks.
        if line_count > MAX_SIMPLE_LINES:
            results.append(ValidationResult(path, Severity.WARN, f"simplified version exceeds line limit: {line_count} > {MAX_SIMPLE_LINES}"))

        for section, aliases in SIMPLE_REQUIRED.items():
            if not has_heading(headings, aliases):
                results.append(ValidationResult(path, Severity.ERROR, f"simplified version missing section: {section}"))

        results.append(ValidationResult(path, Severity.INFO, f"simplified, {line_count} lines"))

    # CLI/single-file projects keep architecture information in AGENTS.md.
    if cli_project and not has_heading(headings, ("Architecture", "架构")):
        results.append(ValidationResult(path, Severity.ERROR, "CLI/single-file project missing Architecture section (replaces docs/ARCHITECTURE.md)"))

    # Validate links inside Quick Entry.
    quick_entry_section = False
    for line in lines:
        if "快速入口" in line or "Quick Entry" in line:
            quick_entry_section = True
            continue
        if quick_entry_section and line.startswith("##"):
            break
        if quick_entry_section:
            for match in QUICK_ENTRY_PATTERN.finditer(line):
                linked_path = match.group(1)
                # Resolve relative to the AGENTS.md containing the link.
                resolved = (path.parent / linked_path).resolve()
                if not resolved.exists():
                    results.append(ValidationResult(path, Severity.WARN, f"dead Quick Entry link: {linked_path}"))

    if require_constraint_mechanism:
        section_lines = find_section_lines(lines, CONSTRAINT_SECTIONS)
        if not section_lines:
            results.append(ValidationResult(
                path, Severity.ERROR,
                "missing Constraint Mechanism section",
            ))
        else:
            mode, config = parse_constraint_mechanism(lines)
            if mode is None:
                results.append(ValidationResult(path, Severity.ERROR, "missing Constraint Mechanism.Mode declaration"))
            elif mode not in VALID_CONSTRAINT_MODES:
                results.append(ValidationResult(
                    path, Severity.ERROR,
                    f"invalid Constraint Mechanism.Mode: {mode} (expected agents-only or linter+agents)",
                ))

            if config is None:
                results.append(ValidationResult(path, Severity.ERROR, "missing Constraint Mechanism.Configuration declaration"))
            elif mode == "agents-only":
                if config != "N/A":
                    results.append(ValidationResult(
                        path, Severity.ERROR,
                        "Constraint Mechanism.Configuration must be `N/A` in agents-only mode",
                    ))
            elif mode == "linter+agents":
                if config == "N/A":
                    results.append(ValidationResult(
                        path, Severity.ERROR,
                        "Constraint Mechanism.Configuration must be a real file path in linter+agents mode",
                    ))
                else:
                    resolved = (path.parent / config).resolve()
                    if not resolved.exists():
                        results.append(ValidationResult(
                            resolved, Severity.ERROR,
                            f"constraint configuration declared by Constraint Mechanism.Configuration does not exist: {config}",
                        ))

    # Root AGENTS.md must retain the hard workflow markers verbatim.
    if require_workflow_constraint:
        missing_markers = [
            marker for marker in WORKFLOW_CONSTRAINT_MARKERS
            if marker not in content
        ]
        if missing_markers:
            results.append(ValidationResult(
                path, Severity.ERROR,
                "missing verbatim workflow hard constraint (see document-templates.md): "
                + "; ".join(missing_markers),
            ))
        missing_execplan_markers = [
            marker for marker in ACTIVE_EXECPLAN_CONSTRAINT_MARKERS
            if marker not in content
        ]
        if missing_execplan_markers:
            results.append(ValidationResult(
                path, Severity.ERROR,
                "missing active ExecPlan execution hard constraint (see document-templates.md): "
                + "; ".join(missing_execplan_markers),
            ))

    return results


def validate_workflow_md(path: Path, agents_md: Path) -> list[ValidationResult]:
    """Validate WORKFLOW.md or its AGENTS.md lightweight replacement."""
    results: list[ValidationResult] = []

    if path.exists():
        line_count = len(path.read_text(encoding="utf-8").splitlines())
        results.append(ValidationResult(path, Severity.INFO, f"{line_count} lines"))
    elif agents_has_lightweight_workflow(agents_md):
        results.append(ValidationResult(
            path,
            Severity.INFO,
            "file absent (AGENTS.md contains a lightweight workflow alternative)",
        ))
    else:
        results.append(ValidationResult(
            path,
            Severity.ERROR,
            "file absent and AGENTS.md has no lightweight workflow alternative",
        ))

    return results


def validate_tasks_md(path: Path, min_level: Severity) -> list[ValidationResult]:
    """Validate TASKS.md file (optional - may be deleted when all tasks complete)."""
    results: list[ValidationResult] = []

    if not path.exists():
        results.append(ValidationResult(path, Severity.INFO, "file absent (the project may be complete)"))
        return results

    content = path.read_text(encoding="utf-8")
    lines = content.splitlines()

    headings = [
        line.strip()[3:].strip()
        for line in lines
        if line.strip().startswith("## ") and not line.strip().startswith("## #")
    ]
    missing_sections = [
        section
        for section, aliases in TASK_REQUIRED_SECTIONS.items()
        if not has_heading(headings, aliases)
    ]
    if missing_sections:
        results.append(ValidationResult(
            path,
            Severity.ERROR,
            f"missing standard sections: {', '.join(missing_sections)}",
        ))

    task_lines = [
        (idx + 1, line.rstrip())
        for idx, line in enumerate(lines)
        if CHECKBOX_PATTERN.match(line)
    ]
    if not task_lines:
        results.append(ValidationResult(path, Severity.ERROR, "no checkbox-formatted tasks found"))

    missing_validation = [
        f"line {line_no}"
        for line_no, line in task_lines
        if TASK_VALIDATION_MARKER not in line
    ]
    if missing_validation:
        results.append(ValidationResult(
            path,
            Severity.ERROR,
            f"tasks missing validation condition (`✅`): {', '.join(missing_validation)}",
        ))

    # Count pending and completed tasks.
    pending = sum(1 for _, line in task_lines if PENDING_TASK_PATTERN.match(line))
    completed = sum(1 for _, line in task_lines if COMPLETED_TASK_PATTERN.match(line))

    results.append(ValidationResult(path, Severity.INFO, f"{pending} pending, {completed} completed"))

    return results


def validate_execution_gates_md(
    path: Path,
    agents_md: Path,
) -> list[ValidationResult]:
    """Validate docs/EXECUTION_GATES.md or its AGENTS.md summary."""
    results: list[ValidationResult] = []

    if path.exists():
        line_count = len(path.read_text(encoding="utf-8").splitlines())
        results.append(ValidationResult(path, Severity.INFO, f"{line_count} lines"))
    elif agents_has_execution_gate_summary(agents_md):
        results.append(ValidationResult(
            path,
            Severity.INFO,
            "file absent (AGENTS.md contains a completion-gate summary)",
        ))
    else:
        results.append(ValidationResult(
            path,
            Severity.ERROR,
            "file absent and AGENTS.md has no completion-gate summary",
        ))

    return results


def validate_architecture_md(path: Path, min_level: Severity, *, cli_project: bool = False) -> list[ValidationResult]:
    """Validate docs/ARCHITECTURE.md file."""
    results: list[ValidationResult] = []

    if not path.exists():
        if cli_project:
            # CLI/single-file projects keep architecture information in AGENTS.md.
            results.append(ValidationResult(path, Severity.INFO, "file absent (CLI/single-file architecture is in AGENTS.md)"))
        else:
            results.append(ValidationResult(path, Severity.ERROR, "file does not exist"))
        return results

    content = path.read_text(encoding="utf-8")

    for concept_group, keywords in ARCHITECTURE_CONCEPT_GROUPS.items():
        if not any(keyword in content for keyword in keywords):
            results.append(ValidationResult(
                path,
                Severity.WARN,
                f"architecture document missing required concept: {concept_group}",
            ))

    line_count = len(content.splitlines())
    results.append(ValidationResult(path, Severity.INFO, f"{line_count} lines"))

    return results


def validate_docs_structure(docs_dir: Path, min_level: Severity, *, cli_project: bool = False) -> list[ValidationResult]:
    """Validate docs/ directory structure."""
    results: list[ValidationResult] = []

    if not docs_dir.exists():
        if cli_project:
            results.append(ValidationResult(docs_dir, Severity.INFO, "docs/ absent (not required for CLI/single-file projects)"))
        else:
            results.append(ValidationResult(docs_dir, Severity.ERROR, "docs/ directory does not exist"))
        return results

    # CLI/single-file projects do not require docs/ARCHITECTURE.md.
    required = [] if cli_project else [
        docs_dir / "ARCHITECTURE.md",
    ]

    for path in required:
        if not path.exists():
            results.append(ValidationResult(path, Severity.ERROR, "required path does not exist"))

    # exec-plans/ is conditional; validate its shape when present.
    exec_plans_dir = docs_dir / "exec-plans"
    if exec_plans_dir.exists():
        for subdir in ["active", "completed"]:
            if not (exec_plans_dir / subdir).exists():
                results.append(ValidationResult(
                    exec_plans_dir / subdir, Severity.WARN,
                    f"exec-plans subdirectory missing: {subdir}"
                ))
    else:
        results.append(ValidationResult(
            exec_plans_dir, Severity.INFO,
            "directory absent (generated only when needed)"
        ))

    return results


def validate_project(root: Path, min_level: Severity) -> list[ValidationResult]:
    """Validate entire project documentation."""
    results: list[ValidationResult] = []

    cli = is_cli_project(root)

    # Core documents.
    agents_md = root / "AGENTS.md"
    workflow_md = root / "WORKFLOW.md"
    validator_script = root / "scripts" / "validate_agents_docs.py"
    tasks_md = root / "TASKS.md"
    # Check legacy naming using actual directory entries. On case-insensitive
    # filesystems, root / "tasks.md" and TASKS.md resolve to the same file.
    root_task_names = {
        p.name for p in root.iterdir()
        if p.is_file() and p.name.lower() == "tasks.md"
    }
    has_canonical_tasks = "TASKS.md" in root_task_names
    legacy_task_names = sorted(n for n in root_task_names if n != "TASKS.md")
    architecture_md = root / "docs" / "ARCHITECTURE.md"
    execution_gates_md = root / "docs" / "EXECUTION_GATES.md"
    docs_dir = root / "docs"

    if not validator_script.exists():
        results.append(ValidationResult(validator_script, Severity.ERROR, "core validator script does not exist"))

    results.extend(
        validate_agents_md(
            agents_md,
            min_level,
            cli_project=cli,
            require_constraint_mechanism=True,
            require_workflow_constraint=True,
        )
    )
    results.extend(validate_workflow_md(workflow_md, agents_md))
    if legacy_task_names and not has_canonical_tasks:
        legacy_path = root / legacy_task_names[0]
        results.append(ValidationResult(
            legacy_path,
            Severity.WARN,
            "legacy tasks.md exists; rename it to root TASKS.md",
        ))
        results.extend(validate_tasks_md(legacy_path, min_level))
    else:
        if legacy_task_names:
            results.append(ValidationResult(
                root / legacy_task_names[0],
                Severity.WARN,
                "legacy tasks.md still exists; root task checklists must use TASKS.md",
            ))
        results.extend(validate_tasks_md(tasks_md, min_level))
    results.extend(validate_architecture_md(architecture_md, min_level, cli_project=cli))
    results.extend(validate_execution_gates_md(execution_gates_md, agents_md))
    results.extend(validate_docs_structure(docs_dir, min_level, cli_project=cli))

    # Validate every child AGENTS.md.
    for agents_path in root.rglob("AGENTS.md"):
        if agents_path != agents_md:
            results.extend(validate_agents_md(agents_path, min_level))

    return results


def filter_by_severity(results: list[ValidationResult], min_level: Severity) -> list[ValidationResult]:
    """Filter results by minimum severity level."""
    severity_order = [Severity.INFO, Severity.WARN, Severity.ERROR]
    min_index = severity_order.index(min_level)
    allowed = severity_order[min_index:]
    return [r for r in results if r.severity in allowed]


def main() -> int:
    # Force UTF-8 so Unicode validation markers remain readable in Windows
    # pipes, CI, Git Bash, and other non-interactive consumers.
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="backslashreplace")
    if hasattr(sys.stderr, "reconfigure"):
        sys.stderr.reconfigure(encoding="utf-8", errors="backslashreplace")

    parser = argparse.ArgumentParser(description="Validate vibe-coding-launcher documentation")
    parser.add_argument(
        "--level",
        choices=["ERROR", "WARN", "INFO"],
        default="INFO",
        help="Minimum severity level to show (default: INFO)",
    )
    parser.add_argument(
        "--project",
        type=Path,
        default=None,
        help="Project root directory (default: script's parent)",
    )
    args = parser.parse_args()

    min_level = Severity(args.level)
    project_root = args.project or ROOT

    if not project_root.exists():
        print(f"[ERROR] Project root not found: {project_root}")
        return 1

    results = validate_project(project_root, min_level)
    filtered = filter_by_severity(results, min_level)

    # Sort by severity.
    severity_order = [Severity.ERROR, Severity.WARN, Severity.INFO]
    filtered.sort(key=lambda r: severity_order.index(r.severity))

    # Print results.
    for result in filtered:
        print(result)

    # Summarize findings.
    error_count = len([r for r in results if r.severity == Severity.ERROR])
    warn_count = len([r for r in results if r.severity == Severity.WARN])

    # Severity filtering changes only which findings are displayed. ERRORs
    # block progress; WARN acceptance is recorded by the surrounding workflow.
    # Keep a nonzero status for WARN so it cannot be overlooked.
    blocking = error_count > 0 or warn_count > 0
    if error_count > 0:
        status = "Validation blocked"
    elif warn_count > 0:
        status = "Validation requires review"
    else:
        status = "Validation complete"
    print(f"\n{status}: {error_count} errors, {warn_count} warnings")

    return 1 if blocking else 0


if __name__ == "__main__":
    sys.exit(main())
